#include "solution.h"

const solve_pfn SOLVE_PFNS[24] = {
    solve_day_1_part_1,
    solve_day_1_part_2,
    solve_day_2_part_1,
    solve_day_2_part_2,
    solve_day_3_part_1,
    solve_day_3_part_2,
    solve_day_4_part_1,
    solve_day_4_part_2,
    solve_day_5_part_1,
    solve_day_5_part_2,
    solve_day_6_part_1,
    solve_day_6_part_2,
    solve_day_7_part_1,
    solve_day_7_part_2,
    solve_day_8_part_1,
    solve_day_8_part_2,
    solve_day_9_part_1,
    solve_day_9_part_2,
    solve_day_10_part_1,
    solve_day_10_part_2,
    solve_day_11_part_1,
    solve_day_11_part_2,
    solve_day_12_part_1,
    solve_day_12_part_2,
};
